"""empty message

Revision ID: 7e850b443b23
Revises: 
Create Date: 2019-11-10 14:50:46.668672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e850b443b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.JSON(), nullable=False),
    sa.Column('posession', sa.JSON(), nullable=False),
    sa.Column('active_rate', sa.Integer(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=20), nullable=False),
    sa.Column('password', sa.Unicode(length=20), nullable=False),
    sa.Column('registerd_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('logs')
    # ### end Alembic commands ###
